name: PHP Preview Server
on: 
  workflow_dispatch:

jobs:
  serve:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install LocalTunnel
        run: sudo npm install -g localtunnel

      - name: Start PHP Server and Tunnel
        run: |
          php -S 0.0.0.0:8080 & 
          sleep 5
          lt --port 8080 > url_preview.txt &
          sleep 8
          
          # Configurar git y subir el archivo con la URL al repo
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add url_preview.txt
          git commit -m "update: serve url"
          git push
          
          # Mantener el tunnel vivo
          tail -f url_preview.txt
