name: Sync to Hugging Face
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Hugging Face Restart
        run: |
          curl -X POST https://huggingface.co/api/spaces/BIGFormacionBran/feelbig-preview/restart \
               -H "Authorization: Bearer ${{ secrets.HF_TOKEN }}"